FROM rust:slim-bookworm

ARG USERNAME
ARG USER_ID
ARG USER_GROUP_ID

COPY --chmod=755 ./scripts/container/install_debian.sh /tmp/install.sh
RUN --mount=type=cache,target=/var/cache/apt /tmp/install.sh

COPY --chmod=755 ./scripts/container/user.sh ./scripts/container/config-environment.sh /tmp/
RUN /tmp/config-environment.sh ${USERNAME} ${USER_ID} ${USER_GROUP_ID} && \
    rm /tmp/*

ENV TERM=xterm-256color

USER ${USERNAME}
