FROM rust:slim-bookworm

ARG INIT_SCRIPT_PATH="./scripts/container/init-debian.sh"

COPY --chmod=744 ${INIT_SCRIPT_PATH} /tmp/initialize.sh
RUN --mount=type=cache,target=/var/cache/apt /tmp/initialize.sh && \
    rm /tmp/initialize.sh && \
    mkdir -p /usr/local/devcontainer

ENV TERM=xterm-256color
