FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim-amd64

COPY --chmod=744 ./scripts/container/init-debian.sh \
    ./scripts/container/user.sh \
    ./scripts/container/create-user.sh \
    /tmp/

RUN --mount=type=cache,target=/var/cache/apt bash /tmp/init-debian.sh && \
    bash /tmp/create-user.sh developer 1000 1000 && \
    rm -r /tmp/*

ENV TERM=xterm-256color
