FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim-amd64

COPY ./scripts/container/init_debian.sh \
    ./scripts/container/user.sh \
    ./scripts/container/create-user.sh \
    ./scripts/container/install-powershell_debian.sh \
    /tmp/

RUN --mount=type=cache,target=/var/cache/apt bash /tmp/init_debian.sh && \
    bash /tmp/create-user.sh developer 1000 1000 && \
    # bash /tmp/install-powershell_debian.sh && \
    rm -r /tmp/*

ENV TERM=xterm-256color
