ARG IMAGE
FROM ${IMAGE}

ARG OWNER
ARG GROUP

COPY --chown=${OWNER}:${GROUP} --chmod=744 ./scripts/container/init-home-vol.sh /tmp/
COPY --chown=${OWNER}:${GROUP} ./resources/citrus-simple.omp.json ./resources/default.zshrc /tmp/home/
RUN mkdir -p /tmp/home/oh-my-posh/ && \
    curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /tmp/home/.local/bin 

ENTRYPOINT [ "/tmp/init-home-vol.sh" ]
