export LS_OPTIONS='--color=auto'
export PATH=~/.local/bin:$PATH
export SHELL=/bin/bash

eval "$(dircolors -b)"

alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

eval "$(oh-my-posh init bash --config ~/.local/share/oh-my-posh/citrus-simple.omp.json)"
eval "$(oh-my-posh completion bash)"
