export LS_OPTIONS='--color=auto'
export PATH=~/.local/bin:$PATH
eval "$(dircolors)"

alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

eval "$(oh-my-posh init bash --config ~/citrus-simple.omp.json)"
eval "$(oh-my-posh completion bash)"
