export PATH=$PATH:~/.local/bin
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=10000

#Uncomment to enable oh-my-zsh
#export ZSH=~/.local/share/oh-my-zsh
#source=$ZSH/oh-my-zosh.sh

eval "$(~/.local/bin/oh-my-posh init zsh --config ~/.local/share/oh-my-posh/citrus-simple.omp.json)"
